### ISSUE TITLE
Program functionality for bad data/empty data/unequal time/voltage arrays interpolation

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/bme590hrm#11]
So for my read_data function (in file_io.py), I have it currently designed that if the program encounters a pair of time/voltage in the data set that contains either a non-convertible string or empty data, that pair is not appended to the overall time and voltage arrays. I understand that theoretically, the program should be able to interpolate any missing or bad data values but I haven't implemented it yet. If I was to stick with my current design, technically would I have to run tests or have functions in the processing code to check if the arrays are the same length? Because if the input time and voltage arrays have different lengths, those extra points in the longer array would not get read in which would automatically cause the two arrays to now be the same length.

**Comment by dward2** [comment]
I'm not 100% sure what you are asking.  If you are reading in time/voltage pairs, and rejecting the pair if either one was bad, then you shouldn't have unequal arrays.  You can always run a check that the time and voltage arrays are the same length, but if you are always adding data to both at the same time, it should be guaranteed.  If there is a different question you are trying to ask, please rephrase.

**Comment by kaseykwong** [comment]
Sorry about my wording. It's so hard to describe questions about code and functionality. That was exactly my question. Since my code is already guaranteeing equal lengths, it seemed pointless to run a check that they are the same length which is why I wasn't sure what sort of test case would be appropriate but I think I have a better idea now. Thank you!
