### ISSUE TITLE
Pytest with Logs

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/bme590hrm#20]
For some of the processing, the program checks for things such as out of range ecg voltages. In my implementation of this (in process_data.py) I simply have the code log warnings about such cases. In my effort to get 100% test coverage, I was wondering how to write a testing function that can check if a log warning was created for a particular event?

**Comment by dward2** [comment]
Rather than testing the logging itself, test the actions that the program performs based on the event that caused the logging.  So, what does your program do if the voltage is out of range?  Write a test to make sure that that action is correct.
