### ISSUE TITLE
Definition of total # of Beat

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/bme590hrm#7]
Is the number of beats considered the number of R-R intervals or the number of R peaks/QRS complexes counted?

**Comment by mlp6** [comment]
That is up to you as the developer.  The end user that we are simulating just cares about beats; your choice of how you want to count a beat is up to you.

**Comment by mlp6** [comment]
As was mentioned in class, in could be associated with a discrete part off the complex, or some other indirect measurement, like integrated energy.
