### ISSUE TITLE
Proper handling on strings in data

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/bme590hrm#8]
From what I saw in test_data30, there are two sets of time/voltage that have the string 'bad data'. What is the appropriate action for this? Throwing an exception and ask for a different file input? Or skip over those points and continue calculating heart rate with the rest of the good data? 

ALSO how does the CODEOWNERS file actually work? I made the codeowners file but it doesn't automatically add everyone as a collaborator.

**Comment by dward2** [comment]
For your first question, skip over the those points and continue calculating heart rate with the rest of the good data.  The objective is how to not let bad data cause a whole file to be lost or the program to crash.

As for the CODEOWNERS file, I was given permission to your repository, so unless you did something else, the inclusion of the CODEOWNERS file did its job.  More info can be found at https://help.github.com/articles/about-codeowners/
